[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push && npx tsx prisma/seed.ts && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
